name: Lint, Build, Start Servers
on: push

jobs:
  build:
    name: Lint, Build, Start Servers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set yarn cache directory
        run: echo "::set-env name=YARN_CACHE::$(yarn cache dir)"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Cache node modules
        id: yarn-workspaces-cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ${{ env.YARN_CACHE }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies on cache miss
        if: steps.yarn-workspaces-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn eslint . --max-warnings 0

      - run: yarn workspace github-profile build
      # Run server for 6 seconds, and succeed if it didn't throw an error
      # https://stackoverflow.com/a/63643845/1268612
      - run: timeout 6 yarn workspace github-profile start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - run: yarn workspace github-profile-experiment build
      - run: timeout 25 yarn workspace github-profile-experiment start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - run: yarn workspace recipes-app build
      - run: timeout 25 yarn workspace recipes-app start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      # No build script required for this package
      - run: timeout 6 yarn workspace recipes-server start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - run: yarn workspace api-routes-graphql build
      - run: timeout 6 yarn workspace api-routes-graphql start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      # No build script required for this package
      - run: timeout 6 yarn workspace basic-server start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

      - run: yarn workspace api-routes-apollo-server-3 build
      - run: timeout 6 yarn workspace api-routes-apollo-server-3 start || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
